# Generated by Django 5.0.6 on 2024-05-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
