# Generated by Django 5.0.6 on 2024-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
